services:
  - type: web
    name: yippee-backend
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    plan: free
    staticPublishPath: static
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVEN_API_KEY
        sync: false
